FUNCTION-POOL ZMC_FGR_SAP04_YEDEK MESSAGE-ID ZMC_SAP04_1.                "MESSAGE-ID ..

* INCLUDE LZMC_FGR_SAP04D...                 " Local class definition

SELECTION-SCREEN BEGIN OF SCREEN 2025 TITLE TEXT-001.
PARAMETERS: p_dist TYPE s_distance.
SELECTION-SCREEN END OF SCREEN 2025.


SELECTION-SCREEN BEGIN OF SCREEN 2026 TITLE TEXT-002.
PARAMETERS: p_url TYPE s_url.
SELECTION-SCREEN END OF SCREEN 2026.

SELECTION-SCREEN BEGIN OF SCREEN 2027 TITLE TEXT-002.
PARAMETERS: p_url_2 TYPE s_url.
SELECTION-SCREEN END OF SCREEN 2027.

SELECTION-SCREEN BEGIN OF SCREEN 2028 TITLE TEXT-003.
PARAMETERS: p_carrid TYPE s_carr_id,
            p_carrnm TYPE s_carrname,
            p_curr   TYPE s_currcode,
            p_url_3  TYPE s_carrurl.
SELECTION-SCREEN END OF SCREEN 2028.

SELECTION-SCREEN BEGIN OF SCREEN 2029 TITLE text-004.

  PARAMETERS: p_color TYPE c LENGTH 4.

SELECTION-SCREEN END OF SCREEN 2029.

"610, 711

SELECTION-SCREEN BEGIN OF SCREEN 2030 TITLE text-005.

  PARAMETERS: p_1 TYPE c LENGTH 1,
              p_2 TYPE c LENGTH 1,
              p_3 TYPE c LENGTH 1.

SELECTION-SCREEN END OF SCREEN 2030.
